### ISSUE TITLE
Support for Lambda layers

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cumulus#1012]
It should be possible to add Lambda layers to a Lambda without having to provide your own cloudformation.template.yml file.   

/cumulus/packages/deployment/app/cloudformation.template.yml:642
```
{{#each lambdas}}
  {{@key}}LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: {{this.bucket}}
        S3Key: {{this.remote}}
      FunctionName: {{../stackName}}-{{@key}}
    {{#if this.layers}}
      Layers:
      {{#each this.layers}}
        - {{this}}
      {{/each}}
    {{/if}}
      Environment:
        Variables:
```

The addition is from `{{#if this.layers}}` to it's ending `{{/if}}`

Then layers can be specified in `lambdas.yml` such as:
```
MyLambda:
  runtime: python3.6
  handler: lambda_function.lambda_handler
  timeout: 300
  memory: 128
  s3Source:
    bucket: '{{buckets.internal.name}}'
    key: deploy/mylambda/0.1.0.zip
  layers:
    - arn:aws:lambda:us-west-2:552188055668:layer:geolambda:1
```

I could make a PR for this, but I'm not sure that the contributing guidelines are still valid given that issues aren't tracked within GitHub.
